config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'erd/page'

  get 'welcome/show'

  get 'page/index'
  root'page#index'
	get 'erd/about'

  resources :studies

  resources :teaches

  resources :attendances

  resources :students

  resources :subjects

  resources :teachers

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :studies
        has_many :subjects, through: :studies
        has_many :attendances
end

app/models/study.rb
class Study < ActiveRecord::Base
  belongs_to :subject
  belongs_to :student
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :teaches
	has_many :teachers, through: :teaches
        has_many :studies
	has_many :students, through: :studies
end

app/models/teach.rb
class Teach < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :subject
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_many :teaches
	has_many :subjects, through: :teaches
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save {self.email = email.downcase }

    validates :name,presence: true,length: maximum: 50
      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      validates :email,presence: true,length: { maximum: 255 },
      format: { with: VALID_EMAIL_REGEX },
      uniqueness: { case_sensitive: false }
end

app/controllers/erd_controller.rb
class ErdController < ApplicationController
	def index
	end
 	
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:show, :edit, :update, :destroy]

  # GET /studies
  # GET /studies.json
  def index
    @studies = Study.all
  end

  # GET /studies/1
  # GET /studies/1.json
  def show
  end

  # GET /studies/new
  def new
    @study = Study.new
  end

  # GET /studies/1/edit
  def edit
  end

  # POST /studies
  # POST /studies.json
  def create
    @study = Study.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to @study, notice: 'Study was successfully created.' }
        format.json { render :show, status: :created, location: @study }
      else
        format.html { render :new }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1
  # PATCH/PUT /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to @study, notice: 'Study was successfully updated.' }
        format.json { render :show, status: :ok, location: @study }
      else
        format.html { render :edit }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.json
  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url, notice: 'Study was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_params
      params.require(:study).permit(:subject_id, :student_id)
    end
end

app/controllers/teaches_controller.rb
class TeachesController < ApplicationController
  before_action :set_teach, only: [:show, :edit, :update, :destroy]

  # GET /teaches
  # GET /teaches.json
  def index
    @teaches = Teach.all
  end

  # GET /teaches/1
  # GET /teaches/1.json
  def show
  end

  # GET /teaches/new
  def new
    @teach = Teach.new
  end

  # GET /teaches/1/edit
  def edit
  end

  # POST /teaches
  # POST /teaches.json
  def create
    @teach = Teach.new(teach_params)

    respond_to do |format|
      if @teach.save
        format.html { redirect_to @teach, notice: 'Teach was successfully created.' }
        format.json { render :show, status: :created, location: @teach }
      else
        format.html { render :new }
        format.json { render json: @teach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teaches/1
  # PATCH/PUT /teaches/1.json
  def update
    respond_to do |format|
      if @teach.update(teach_params)
        format.html { redirect_to @teach, notice: 'Teach was successfully updated.' }
        format.json { render :show, status: :ok, location: @teach }
      else
        format.html { render :edit }
        format.json { render json: @teach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teaches/1
  # DELETE /teaches/1.json
  def destroy
    @teach.destroy
    respond_to do |format|
      format.html { redirect_to teaches_url, notice: 'Teach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teach
      @teach = Teach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teach_params
      params.require(:teach).permit(:teacher_id, :subject_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/erd_helper.rb
module ErdHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/teaches_helper.rb
module TeachesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/studies/_form.html.erb
<%= form_for(@study) do |f| %>

  <% if @study.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study.errors.count, "error") %> prohibited this study from being saved:</h2>

      <ul>
      <% @study.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject_id %><br>
    <%= f.collection_select(:subject_id, Subject.all, :id, :subject_title) %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.collection_select(:student_id, Student.all, :id, :student_name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/studies/edit.html.erb
<h1>Editing Study</h1>

<%= render 'form' %>

<%= link_to 'Show', @study %> |
<%= link_to 'Back', studies_path %>

app/views/studies/index.html.erb
<p id="notice"><%= notice %></p>

<center>
<h1>Listing Studies</h1></center>

<table  border="1" bordercolor=" #FFD700" width="10" align="center">
  <thead>
    <tr>
	<th>Study ID</th>
      <th>Subject</th>
      <th>Student</th>
      <th colspan="3">Edit</th>
    </tr>
  </thead>

  <tbody>
    <% @studies.each do |study| %>
      <tr>
	<td><%= study.id %></td>
        <td><%= study.subject.subject_title %></td>
        <td><%= study.student.student_name %></td>
        <td><%= link_to 'Show', study %></td>
        <td><%= link_to 'Edit', edit_study_path(study) %></td>
        <td><%= link_to 'Destroy', study, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Study', new_study_path %>

app/views/studies/new.html.erb
<h1>New Study</h1>

<%= render 'form' %>

<%= link_to 'Back', studies_path %>

app/views/studies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @study.subject.subject_title %>
</p>

<p>
  <strong>Student:</strong>
  <%= @study.student.student_name %>
</p>

<%= link_to 'Edit', edit_study_path(@study) %> |
<%= link_to 'Back', studies_path %>

app/views/teaches/_form.html.erb
<%= form_for(@teach) do |f| %>

  <% if @teach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teach.errors.count, "error") %> prohibited this teach from being saved:</h2>

      <ul>
      <% @teach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :teacher_id %><br>
    <%= f.collection_select(:teacher_id, Teacher.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :subject_id %><br>
    <%= f.collection_select(:subject_id, Subject.all, :id, :subject_title) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teaches/edit.html.erb
<h1>Editing Teach</h1>

<%= render 'form' %>

<%= link_to 'Show', @teach %> |
<%= link_to 'Back', teaches_path %>

app/views/teaches/index.html.erb
<p id="notice"><%= notice %></p>

<center>
<h1>Listing Teaches</h1></center>

<table  border="4" bordercolor=" #FFD700" align="center" size="20">
  <thead>
    <tr>
      <th>Teach ID</th>
      <th>Teacher</th>
      <th>Subject</th>
      <th colspan="3">Edit</th>
    </tr>
  </thead>

  <tbody>
    <% @teaches.each do |teach| %>
      <tr>
	<td><%= teach.teacher.id %></td>
        <td><%= teach.teacher.name %></td>
        <td><%= teach.subject.subject_title %></td>
        <td><%= link_to 'Show', teach %></td>
        <td><%= link_to 'Edit', edit_teach_path(teach) %></td>
        <td><%= link_to 'Destroy', teach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teach', new_teach_path %>

app/views/teaches/new.html.erb
<h1>New Teach</h1>

<%= render 'form' %>

<%= link_to 'Back', teaches_path %>

app/views/teaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teacher:</strong>
  <%= @teach.teacher %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @teach.subject %>
</p>

<%= link_to 'Edit', edit_teach_path(@teach) %> |
<%= link_to 'Back', teaches_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>