config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'erd/page'

  get 'welcome/show'

  get 'page/index'
  root'page#index'
	get 'erd/about'

  resources :studies

  resources :teaches

  resources :attendances

  resources :students

  resources :subjects

  resources :teachers

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :studies
        has_many :subjects, through: :studies
        has_many :attendances
end

app/models/study.rb
class Study < ActiveRecord::Base
  belongs_to :subject
  belongs_to :student
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :teaches
	has_many :teachers, through: :teaches
        has_many :studies
	has_many :students, through: :studies
end

app/models/teach.rb
class Teach < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :subject
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_many :teaches
	has_many :subjects, through: :teaches
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save {self.email = email.downcase }

    validates :name,presence: true,length: maximum: 50
      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      validates :email,presence: true,length: { maximum: 255 },
      format: { with: VALID_EMAIL_REGEX },
      uniqueness: { case_sensitive: false }
end

app/controllers/erd_controller.rb
class ErdController < ApplicationController
	def index
	end
 	
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/erd_helper.rb
module ErdHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/teaches_helper.rb
module TeachesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
	<div class="footer">Copyright@2015 Shaista Razzaq  Mcs (Evening) Universty Of Balochistan</div>

app/views/layouts/_header.html.erb
<div id="container">
<div class="banner">
<%=image_tag("on.jpg", :alt=>"user", :class=>"round", :width=>"900px", :height=>"150", :align=>"center")%></div>

<div class="nav">

<tr>
     <td><%= link_to   'Home  |', root_path%></td>
     <td><%= link_to'student  |', students_path%></td>
     <td><%= link_to 'subject |', subjects_path%></td>
     <td><%= link_to 'teacher |', teachers_path%></td>
     <td><%= link_to 'attendance |', attendances_path%></td>
     <td><%= link_to 'teach |', teaches_path%></td>
     <td><%= link_to 'study |', studies_path%></td>
     <td><%= link_to 'show Attendance |', welcome_show_path%></td>
     <td><%= link_to 'ERD |', erd_page_path%></td>

</tr>
</div>
	<div class="content-wrapper">
	<div class="col1"> <%= yield %>
	</div>
	<div class="col2"> <img src="images/uni.jpeg" width="178" height="100">
	<p><a href="http://http://www.uob.edu.pk/">Visit UOB</a></p><br>

	<img src="images/ror.jpeg" width="178" height="100">
        
        <p><a href="http://www.tutorialspoint.com/ruby-on-rails/">Visit ROR tutorial</a></p><br>

	<img src="images/ff.jpg" width="178" height="100">
        
        <p><a href="http://www.facebook.com">Visit FaceBook</a></p><br>




	
	
</div>

</div></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Miniaap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<style>
 body{background-color:  black}
 </style>
<body>


	<%=render 'layouts/header' %>
   
      



	<%= render 'layouts/footer' %>	


</body>

</html>

app/views/page/index.html.erb
<h1><center>welcome to Online Attendance system</center></h1>
<h2> <center> Department Of Computer science </center></h2>
<h3><center> Universty Of Balochistan</center></h3>

<center>
<body background-color="green">

<img src="images/uob.jpeg" width="620" height="400">
</center> 